name: Harris Lapiroff
markdown: kramdown
include: [".well-known"]
exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "node_modules"
  - "vendor/bundle/"
  - "vendor/cache/"
  - "vendor/gems/"
  - "vendor/ruby/"
  - "CNAME"
  - "README.md"
baseurl: 'https://chromamine.com'
